COM-6264: Specify how to get and set up fluster on a local machine
fluendo/fluster pull request #129
Opened 2023-03-10 10:20 UTC by german-martinez

2023-03-10 11:23 UTC, rgonzalezfluendo commented on README.md
> +- Clone the repository: gh repo clone fluendo/fluster
```suggestion
- Clone the repository: `git clone https://github.com/fluendo/fluster.git` 
```

Better to use `git` than `gh`. It's more generic and nor only related with GitHub.

2023-03-13 12:22 UTC, mdimopoulos requested changes
Minor grammatical issue

2023-03-13 12:22 UTC, mdimopoulos commented on README.md
> +- [Release source code](https://github.com/fluendo/fluster/releases) assets is available in the following formats zip, tar.gz
```suggestion
- [Release source code](https://github.com/fluendo/fluster/releases) assets are available in the following formats zip, tar.gz
```

2023-03-14 13:12 UTC, mdimopoulos requested changes
Minor change is needed to make sure README appears correctly

2023-03-14 13:12 UTC, mdimopoulos commented on README.md
> +  - [How to get started] (#how-to-get-started)
```suggestion
  - [How to get started](#how-to-get-started)
```

2023-03-14 14:59 UTC, merged