COM-12568: Replace pylint/black with ruff
fluendo/fluster pull request #208
Opened 2024-11-14 15:51 UTC by mdimopoulos

2024-12-02 16:32 UTC, mcesariniflu commented on fluster/main.py
> +        fluster.list_test_suites(show_test_vectors=args.testvectors, test_suites=args.testsuites)
Is "`codec=args.codec,`" missing, or is not necessary anymore?
Also in line 352.

2024-12-03 16:38 UTC, mcesariniflu requested changes
just one comment in fluster/main.py file in lines 351 and 352

2024-12-04 08:39 UTC, mcesariniflu approved these changes

2024-12-04 09:40 UTC, mdimopoulos commented on fluster/decoders/av1_aom.py
> +        if output_format in [OutputFormat.YUV420P, OutputFormat.YUV420P10LE]:
Nope not related. This is a modification i did while testing out the generator after i had adapted it to conform to ruff standards.

2024-12-04 09:44 UTC, mdimopoulos commented on test_suites/av1/AV1-TEST-VECTORS.json
Nope not related. I executed the test suite generator script and it found these extra test vectors. Maybe they were added remotely since the last generation of this test suite.
Is this an issue? What changes do you want me to do, i don't understand

2024-12-04 10:09 UTC, rgonzalezfluendo commented on test_suites/av1/AV1-TEST-VECTORS.json
The desired solution would be to have different atomic commits with each change.

* One adding ruff
* Other with the new format generated after running ruff. To be able to use [.git-blame-ignore-revs](https://graphite.dev/guides/git-blame-ignore-revs) with this commits.
* Other with those new things.

2024-12-04 10:10 UTC, rgonzalezfluendo reviewed
No blocking the PR

2024-12-04 10:31 UTC, mdimopoulos commented on test_suites/av1/AV1-TEST-VECTORS.json
Ah ok, the logic i followed is different because i wanted to have the CI green after each commit.

Commit 1: Replaced other tools with ruff and applied relevant changes to python scripts (bullet points 1+2)
Commit 2: cleanup dead code comments related to old tools
Commit 3: extended scope of ruff and fixed some issues with generator scripts

What i can do is split commit 3 into 2 parts. I would not split commit 1 into parts now after the fact, it's an overkill. If we don't care about having green CI after each commit then i can adapt my way of working for the future. Let me know please

2024-12-04 10:52 UTC, rgonzalezfluendo commented on test_suites/av1/AV1-TEST-VECTORS.json
Ok. I understand your position.

IMHO having atomic commits is more important to have the CI green after each commit. But it is a personal opinion.

cc @carlosfg-flu (lover of atomic commits)

2024-12-04 10:58 UTC, mdimopoulos commented on test_suites/av1/AV1-TEST-VECTORS.json
Ok done deal, i'll start going down the path of more atomic commits.
Having green CI after each commit can prevent confusion on the part of the reviewer, that's the reason i have been working like that as much as possible.

2024-12-09 18:05 UTC, merged