gstreamer: Fix element detection on Windows
fluendo/fluster pull request #75
Opened 2021-07-16 17:59 UTC by seungha-yang

To execute binary, full name with file extension is required.

cc @ndufresne

2021-07-16 18:28 UTC, ndufresne commented
Looks fair to me, I didn't think about that when I implemented this.

2021-07-19 08:18 UTC, pamarcos requested changes
Nice catch! Fortunately, we already had to deal with this in the past, so there's a utility function in `utils.normalize_binary_cmd` that is used exactly for this purpose. Please, feel free to use it :)

2021-07-19 08:18 UTC, pamarcos commented on fluster/decoders/gstreamer.py
> +    inspect_exe = 'gst-inspect-1.0'
```suggestion
    from fluster.utils import normalize_binary_cmd
    inspect_exe = utils.normalize_binary_cmd('gst-inspect-1.0')
```

2021-07-19 16:46 UTC, seungha-yang commented on fluster/decoders/gstreamer.py
> +    inspect_exe = 'gst-inspect-1.0'
indeed, thanks for the suggestion :)

2021-07-19 16:59 UTC, pamarcos approved these changes
Perfect @seungha-yang! Thanks a mill for your fix

2021-07-19 17:00 UTC, merged